name: generate_reports
channels:
  - conda-forge
  - bioconda
  - anaconda
  - epi2melabs
  - defaults
dependencies:
  - pandas
  - numpy
  - openpyxl
  - wkhtmltopdf
  - python-pdfkit
  - pip
  - pip:
    - git+https://github.com/sheffield-bioinformatics-core/aplanat_UoS.git