name: generate_reports
channels:
  - conda-forge
  - bioconda
  - anaconda
  - epi2melabs
  - defaults
dependencies:
  - pandas
  - numpy
  - epi2melabs::aplanat
  - openpyxl
  - wkhtmltopdf
  - python-pdfkit